/**
* Autogenerated by Thrift Compiler (0.13.0)
*
* DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*  @generated
*/
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


namespace model
{

#if !SILVERLIGHT
    [Serializable]
#endif
    public partial class EmployeeDTO : TBase
    {
        private int _id;
        private string _username;
        private string _password;

        public int Id
        {
            get
            {
                return _id;
            }
            set
            {
                __isset.id = true;
                this._id = value;
            }
        }

        public string Username
        {
            get
            {
                return _username;
            }
            set
            {
                __isset.username = true;
                this._username = value;
            }
        }

        public string Password
        {
            get
            {
                return _password;
            }
            set
            {
                __isset.password = true;
                this._password = value;
            }
        }


        public Isset __isset;
#if !SILVERLIGHT
        [Serializable]
#endif
        public struct Isset
        {
            public bool id;
            public bool username;
            public bool password;
        }

        public EmployeeDTO()
        {
        }

        public void Read(TProtocol iprot)
        {
            iprot.IncrementRecursionDepth();
            try
            {
                TField field;
                iprot.ReadStructBegin();
                while (true)
                {
                    field = iprot.ReadFieldBegin();
                    if (field.Type == TType.Stop)
                    {
                        break;
                    }
                    switch (field.ID)
                    {
                        case 1:
                            if (field.Type == TType.I32)
                            {
                                Id = iprot.ReadI32();
                            }
                            else
                            {
                                TProtocolUtil.Skip(iprot, field.Type);
                            }
                            break;
                        case 2:
                            if (field.Type == TType.String)
                            {
                                Username = iprot.ReadString();
                            }
                            else
                            {
                                TProtocolUtil.Skip(iprot, field.Type);
                            }
                            break;
                        case 3:
                            if (field.Type == TType.String)
                            {
                                Password = iprot.ReadString();
                            }
                            else
                            {
                                TProtocolUtil.Skip(iprot, field.Type);
                            }
                            break;
                        default:
                            TProtocolUtil.Skip(iprot, field.Type);
                            break;
                    }
                    iprot.ReadFieldEnd();
                }
                iprot.ReadStructEnd();
            }
            finally
            {
                iprot.DecrementRecursionDepth();
            }
        }

        public void Write(TProtocol oprot)
        {
            oprot.IncrementRecursionDepth();
            try
            {
                TStruct struc = new TStruct("EmployeeDTO");
                oprot.WriteStructBegin(struc);
                TField field = new TField();
                if (__isset.id)
                {
                    field.Name = "id";
                    field.Type = TType.I32;
                    field.ID = 1;
                    oprot.WriteFieldBegin(field);
                    oprot.WriteI32(Id);
                    oprot.WriteFieldEnd();
                }
                if (Username != null && __isset.username)
                {
                    field.Name = "username";
                    field.Type = TType.String;
                    field.ID = 2;
                    oprot.WriteFieldBegin(field);
                    oprot.WriteString(Username);
                    oprot.WriteFieldEnd();
                }
                if (Password != null && __isset.password)
                {
                    field.Name = "password";
                    field.Type = TType.String;
                    field.ID = 3;
                    oprot.WriteFieldBegin(field);
                    oprot.WriteString(Password);
                    oprot.WriteFieldEnd();
                }
                oprot.WriteFieldStop();
                oprot.WriteStructEnd();
            }
            finally
            {
                oprot.DecrementRecursionDepth();
            }
        }

        public override string ToString()
        {
            StringBuilder __sb = new StringBuilder("EmployeeDTO(");
            bool __first = true;
            if (__isset.id)
            {
                if (!__first) { __sb.Append(", "); }
                __first = false;
                __sb.Append("Id: ");
                __sb.Append(Id);
            }
            if (Username != null && __isset.username)
            {
                if (!__first) { __sb.Append(", "); }
                __first = false;
                __sb.Append("Username: ");
                __sb.Append(Username);
            }
            if (Password != null && __isset.password)
            {
                if (!__first) { __sb.Append(", "); }
                __first = false;
                __sb.Append("Password: ");
                __sb.Append(Password);
            }
            __sb.Append(")");
            return __sb.ToString();
        }

    }


}
