
/**
* Autogenerated by Thrift Compiler (0.13.0)
*
* DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*  @generated
*/
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;
namespace model
{
#if !SILVERLIGHT
    [Serializable]
#endif
    public partial class ShowDTO : TBase
    {
        private int _id;
        private string _dataTimp;
        private string _location;
        private int _nrAvailableSeats;
        private int _nrSoldSeats;
        private string _artistName;

        public int Id
        {
            get
            {
                return _id;
            }
            set
            {
                __isset.id = true;
                this._id = value;
            }
        }

        public string DataTimp
        {
            get
            {
                return _dataTimp;
            }
            set
            {
                __isset.dataTimp = true;
                this._dataTimp = value;
            }
        }

        public string Location
        {
            get
            {
                return _location;
            }
            set
            {
                __isset.location = true;
                this._location = value;
            }
        }

        public int NrAvailableSeats
        {
            get
            {
                return _nrAvailableSeats;
            }
            set
            {
                __isset.nrAvailableSeats = true;
                this._nrAvailableSeats = value;
            }
        }

        public int NrSoldSeats
        {
            get
            {
                return _nrSoldSeats;
            }
            set
            {
                __isset.nrSoldSeats = true;
                this._nrSoldSeats = value;
            }
        }

        public string ArtistName
        {
            get
            {
                return _artistName;
            }
            set
            {
                __isset.artistName = true;
                this._artistName = value;
            }
        }


        public Isset __isset;
#if !SILVERLIGHT
        [Serializable]
#endif
        public struct Isset
        {
            public bool id;
            public bool dataTimp;
            public bool location;
            public bool nrAvailableSeats;
            public bool nrSoldSeats;
            public bool artistName;
        }

        public ShowDTO()
        {
        }

        public void Read(TProtocol iprot)
        {
            iprot.IncrementRecursionDepth();
            try
            {
                TField field;
                iprot.ReadStructBegin();
                while (true)
                {
                    field = iprot.ReadFieldBegin();
                    if (field.Type == TType.Stop)
                    {
                        break;
                    }
                    switch (field.ID)
                    {
                        case 1:
                            if (field.Type == TType.I32)
                            {
                                Id = iprot.ReadI32();
                            }
                            else
                            {
                                TProtocolUtil.Skip(iprot, field.Type);
                            }
                            break;
                        case 2:
                            if (field.Type == TType.String)
                            {
                                DataTimp = iprot.ReadString();
                            }
                            else
                            {
                                TProtocolUtil.Skip(iprot, field.Type);
                            }
                            break;
                        case 3:
                            if (field.Type == TType.String)
                            {
                                Location = iprot.ReadString();
                            }
                            else
                            {
                                TProtocolUtil.Skip(iprot, field.Type);
                            }
                            break;
                        case 4:
                            if (field.Type == TType.I32)
                            {
                                NrAvailableSeats = iprot.ReadI32();
                            }
                            else
                            {
                                TProtocolUtil.Skip(iprot, field.Type);
                            }
                            break;
                        case 5:
                            if (field.Type == TType.I32)
                            {
                                NrSoldSeats = iprot.ReadI32();
                            }
                            else
                            {
                                TProtocolUtil.Skip(iprot, field.Type);
                            }
                            break;
                        case 6:
                            if (field.Type == TType.String)
                            {
                                ArtistName = iprot.ReadString();
                            }
                            else
                            {
                                TProtocolUtil.Skip(iprot, field.Type);
                            }
                            break;
                        default:
                            TProtocolUtil.Skip(iprot, field.Type);
                            break;
                    }
                    iprot.ReadFieldEnd();
                }
                iprot.ReadStructEnd();
            }
            finally
            {
                iprot.DecrementRecursionDepth();
            }
        }

        public void Write(TProtocol oprot)
        {
            oprot.IncrementRecursionDepth();
            try
            {
                TStruct struc = new TStruct("ShowDTO");
                oprot.WriteStructBegin(struc);
                TField field = new TField();
                if (__isset.id)
                {
                    field.Name = "id";
                    field.Type = TType.I32;
                    field.ID = 1;
                    oprot.WriteFieldBegin(field);
                    oprot.WriteI32(Id);
                    oprot.WriteFieldEnd();
                }
                if (DataTimp != null && __isset.dataTimp)
                {
                    field.Name = "dataTimp";
                    field.Type = TType.String;
                    field.ID = 2;
                    oprot.WriteFieldBegin(field);
                    oprot.WriteString(DataTimp);
                    oprot.WriteFieldEnd();
                }
                if (Location != null && __isset.location)
                {
                    field.Name = "location";
                    field.Type = TType.String;
                    field.ID = 3;
                    oprot.WriteFieldBegin(field);
                    oprot.WriteString(Location);
                    oprot.WriteFieldEnd();
                }
                if (__isset.nrAvailableSeats)
                {
                    field.Name = "nrAvailableSeats";
                    field.Type = TType.I32;
                    field.ID = 4;
                    oprot.WriteFieldBegin(field);
                    oprot.WriteI32(NrAvailableSeats);
                    oprot.WriteFieldEnd();
                }
                if (__isset.nrSoldSeats)
                {
                    field.Name = "nrSoldSeats";
                    field.Type = TType.I32;
                    field.ID = 5;
                    oprot.WriteFieldBegin(field);
                    oprot.WriteI32(NrSoldSeats);
                    oprot.WriteFieldEnd();
                }
                if (ArtistName != null && __isset.artistName)
                {
                    field.Name = "artistName";
                    field.Type = TType.String;
                    field.ID = 6;
                    oprot.WriteFieldBegin(field);
                    oprot.WriteString(ArtistName);
                    oprot.WriteFieldEnd();
                }
                oprot.WriteFieldStop();
                oprot.WriteStructEnd();
            }
            finally
            {
                oprot.DecrementRecursionDepth();
            }
        }

        public override string ToString()
        {
            StringBuilder __sb = new StringBuilder("ShowDTO(");
            bool __first = true;
            if (__isset.id)
            {
                if (!__first) { __sb.Append(", "); }
                __first = false;
                __sb.Append("Id: ");
                __sb.Append(Id);
            }
            if (DataTimp != null && __isset.dataTimp)
            {
                if (!__first) { __sb.Append(", "); }
                __first = false;
                __sb.Append("DataTimp: ");
                __sb.Append(DataTimp);
            }
            if (Location != null && __isset.location)
            {
                if (!__first) { __sb.Append(", "); }
                __first = false;
                __sb.Append("Location: ");
                __sb.Append(Location);
            }
            if (__isset.nrAvailableSeats)
            {
                if (!__first) { __sb.Append(", "); }
                __first = false;
                __sb.Append("NrAvailableSeats: ");
                __sb.Append(NrAvailableSeats);
            }
            if (__isset.nrSoldSeats)
            {
                if (!__first) { __sb.Append(", "); }
                __first = false;
                __sb.Append("NrSoldSeats: ");
                __sb.Append(NrSoldSeats);
            }
            if (ArtistName != null && __isset.artistName)
            {
                if (!__first) { __sb.Append(", "); }
                __first = false;
                __sb.Append("ArtistName: ");
                __sb.Append(ArtistName);
            }
            __sb.Append(")");
            return __sb.ToString();
        }

    }

}
